### ISSUE TITLE
Pulling from this codebase back to wynnbuilder main

### ISSUE THREAD

**Issue by hppeng-wynn** [davidwnguyen/davidwnguyen.github.io#1]
Hi,

Would you mind if I merged code from here with wynnbuilder?

(Or, more easily, would you want to collaborate on updating the site? I noticed you have a good grasp on the codebase already :') )

-hpp

**Comment by davidwnguyen** [comment]
I'd be perfectly fine with you merging from here! A fair warning that a few things aren't fully accurate though, like the crafted item powder nerfs. I'd also like to collaborate in the future.

**Comment by hppeng-wynn** [comment]
Yeah, actually how did you compute the crafted item powder nerfs?

Did you go off the item display or damage from damage dummies? (Or did something else change in the past few weeks...months? it's been awhile since the wb team has done ingame testing with them...)

**Comment by davidwnguyen** [comment]
I went off the item display; in the patch notes it said that ingredient powders are half as effective and that the double post-powder application was fixed. Not exactly sure how the conversions were changed because there is a noticable difference between in-game and the nerfs I applied.

Post-Powder
==
![image](https://github.com/user-attachments/assets/0cd15591-59cd-46a7-92db-d6dc206485b6)
![image](https://github.com/user-attachments/assets/fa290d55-0f35-4d01-82b1-ccd1b2e080c7)
==
Pre-Powder
==
![image](https://github.com/user-attachments/assets/5ffa0f74-7c1f-4d6d-b6f9-55c456866254)
![image](https://github.com/user-attachments/assets/89ff3798-9d5e-4833-870b-fbf11539427e)


The baseDPS is relatively similar though? 
Spear Recipe:
https://hppeng-wynn.github.io/crafter/#1+c+i+o+u++629Y92

**Comment by hppeng-wynn** [comment]
Nevermind, above comment is wrong; talked with IMs and seems like wynnbuilder powder app has been off for awhile now

Would want to test it eventually...

**Comment by hppeng-wynn** [comment]
I merged in most of your updates, do you have a discord handle (or something else) that you would want me to give you a shoutout for?

Also, for future collaboration how would you want to communicate? I'm primarily on Discord myself, we could discuss splitting things 👀 

There's at least two(three?) pretty big things going forward that honestly i don't think i have the bandwidth to handle quickly mm
